project_name: falcon-cli

env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - REPO=github.com/crowdstrike/falcon-cli

builds:
  - env:
      - CGO_ENABLED=0
    binary: falcon
    main: ./cmd/falcon/main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ .Env.PWD }}
    gcflags:
      - all=-trimpath={{ .Env.PWD }}
    ldflags:
      - -s -w
      - -X {{ .Env.REPO }}/pkg/version.Version={{ .Version }}
      - -X {{ .Env.REPO }}/pkg/version.GitVersion={{ .Tag }}
      - -X {{ .Env.REPO }}/pkg/version.GitCommit={{ .Commit }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_ppc64le
      - linux_s390x
      - windows_amd64
      - windows_arm64
archives:
  - id: binaries
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  - id: archives
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - dist/CHANGELOG.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - package_name: falcon-cli
    file_name_template: "{{ .PackageName }}-{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .Release}}.{{ .Arch }}"
    replacements:
      amd64: x86_64
      arm64: aarch64
      386: i386
    vendor: CrowdStrike Inc.
    homepage: https://crowdstrike.com/
    maintainer: cloud-integrations@crowdstrike.com
    description: |-
      The CrowdStrike Falcon CLI allows you to work effortlessly with the CrowdStrike Falcon platform.
    license: MIT
    release: "1"
    formats:
      - deb
      - rpm
      - archlinux
    rpm:
      summary: The CrowdStrike Falcon CLI tool
